### ISSUE TITLE
sql-model去除ONLY_FULL_GROUP_BY

### ISSUE THREAD

**Issue by corin11** [suyar/docker-php-env#1]
MYSQL_VERSION=8.0.40-debian
Mysql容器内：/etc/mysql/conf.d/mysql.cnf相关sql-mode设置：
```
sql-mode                = NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO
```
查询sql_mode:
show variables like '%sql_mode';
显示为：ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
需要将此sql-mode写入到/etc/mysql/my.conf中：
```
[mysqld]
pid-file        = /var/run/mysqld/mysqld.pid
socket          = /var/run/mysqld/mysqld.sock
datadir         = /var/lib/mysql
secure-file-priv= NULL
sql-mode                = NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO
```
再次查询sql_mode：
show variables like '%sql_mode';
显示为：
STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION

**Comment by suyar** [comment]
@tangshuanglong  这里有默认配置：
![image](https://github.com/user-attachments/assets/4b40b13d-d605-49e3-a711-2e726347f744)

```
docker compose logs -f mysql
```

看下日志，是不是因为配置文件的权限问题导致挂载失败

**Comment by corin11** [comment]
Mysql日记显示：
dpe_mysql  | mysqld: [Warning] World-writable config file '/etc/mysql/conf.d/mysql.cnf' is ignored.
查看/etc/mysql下各文件权限：
***@***.***:/etc/mysql# ls -l
total 16
drwxr-xr-x 1 root root 4096 Oct 17 09:30 conf.d
-rw-r--r-- 1 root root 1205 Dec  4 23:09 my.cnf
-rw-r--r-- 1 root root 1498 Sep 18 18:42 my.cnf.fallback
-rw-r--r-- 1 root root 1080 Dec  4 22:56 my.cnf_bak
***@***.***:/etc/mysql# cd conf.d/
***@***.***:/etc/mysql/conf.d# ls -l
total 4
-rw-r--r-- 1 root root  45 Oct 17 09:30 docker.cnf
-rwxrwxrwx 1 root root 485 Dec  4 23:09 mysql.cnf





在 2024-12-05 14:34:13，"suyar" ***@***.***> 写道：

@tangshuanglong 这里有默认配置：
image.png (view on web)

docker compose logs -f mysql


看下日志，是不是因为配置文件的权限问题导致挂载失败

**Comment by suyar** [comment]
![image](https://github.com/user-attachments/assets/f4810be9-24c8-4a27-813d-c1d8d4ed8e9a)
@tangshuanglong  mysql默认会忽略全局可写的配置文件，请注意挂载时候的文件权限，或者直接在容器内
````
chmod 644 /etc/mysql/conf.d/mysql.cnf
```

不过建议还是在宿主机（非windows）配置好挂载文件权限后再重启下mysql

**Comment by corin11** [comment]
谢谢，我已经搞定了











在 2024-12-05 18:05:23，"suyar" ***@***.***> 写道：

image.png (view on web)
@tangshuanglong mysql默认会忽略全局可写的配置文件，请注意挂载时候的文件权限，或者直接在容器内

chmod 644 /etc/mysql/conf.d/mysql.cnf
```

不过建议还是在宿主机（非windows）配置好挂载文件权限后再重启下mysql


—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>
